### ISSUE TITLE
Hay una referencia circular entre dos ficheros

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani#1]
Entre los ficheros [`db/models/file.js`](https://github.com/ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani/blob/master/db/models/file.js), [`db/models/user.js`](https://github.com/ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani/blob/master/db/models/user.js) hay una referencia circular.

Hemos hecho las condiciones de integridad de cada colección con el middleware `pre` de mongoose. El problema es que para poder llevar a cabo estas condiciones, necesitamos en [`db/models/file.js`](https://github.com/ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani/blob/master/db/models/file.js) requerir a [`db/models/user.js`](https://github.com/ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani/blob/master/db/models/user.js) y vice versa. 

El error se produce en [`db/models/user.js`](https://github.com/ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani/blob/master/db/models/user.js), que no hace el require correctamente. Hemos probado a hacer un `console.log` de la constante `File` y nos devuelve un hash vacío, en vez del modelo de User.

/cc @crguezl

**Comment by crguezl** [comment]
Por lo pronto observo que en `file.js` dice:

``` javascript
 let FileShema = mongoose.Schema({
        filename: String,
        data: String,
        owner: [{ type: Schema.Types.ObjectId, ref: 'User' }]
    });
```

lo que no me cuadra. `owner` debería ser uno sólo, no un array:

``` javascript
 let FileShema = mongoose.Schema({
        filename: String,
        data: String,
        owner: { type: Schema.Types.ObjectId, ref: 'User' }
    });
```

**Comment by DanielRamosAcosta** [comment]
@crguezl cierto a @alu0100505078 y a mí se nos escaparon los corchetes al copiar de los Usuarios :hushed:

**Comment by crguezl** [comment]
Uhm... He juntado los dos modelos en un solo fichero y hecho consistente los `require` y cuando hago:

``` javascript
console.log("File = ",util.inspect(File, {depth: null}));
```

me sale el objeto `File` (enorme)

**Comment by crguezl** [comment]
pero si, tal y como lo tienen sale vacío el objeto

**Comment by DanielRamosAcosta** [comment]
Nosotros en cuando vimos que no nos funcionaba y que teníamos problemas en al requerir los modelos de forma circular, unimos los dos modelos en el mismo fichero y retornábamos un hash con ambos. Pero lo deshicimos porque pensábamos que no era muy escalable tener todos los modelos en el mismo fichero.

¿Buscamos otra solución o lo ponemos en el mismo fichero @crguezl?

**Comment by crguezl** [comment]
En el mismo fichero. Las dos colecciones están muy acopladas
