### ISSUE TITLE
Cambiar código de error en la subida de ficheros

### ISSUE THREAD

**Issue by Rafaherrero** [ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani#3]
Cuando se sube más de un fichero con el mismo nombre, el error que devuelve el servidor no es el correcto, por lo que no se puede mostrar un aviso correctamente.

**Comment by PedroRamosRguez** [comment]
@Rafaherrero  ya están arreglados los códigos de errores cuando los ficheros son iguales, y además arreglamos otros en el commit b28064c

**Comment by DanielRamosAcosta** [comment]
@Rafaherrero revisa que te lo devuelva bien para ver si podemos cerrar esto

**Comment by Rafaherrero** [comment]
@alu0100505078, @DanielRamosAcosta Perfecto
