### ISSUE TITLE
Se inicia sesion sin registrar usuario

### ISSUE THREAD

**Issue by PedroRamosRguez** [ULL-ESIT-GRADOII-DSI/mongoose-y-populations-rafa-pedro-dani#4]
@Rafaherrero Si se pone registrarse usuario y no se crea nada, y luego le das a iniciar sesion... se accede a la aplicación pero no se muestra nada. Y si pruebo a insertar un fichero, express devuelve el error correctamente pero se muestra en el cliente como que el fichero existe.

**Comment by Rafaherrero** [comment]
@alu0100505078 Listo! Ahora es obligatorio introducir un nombre Y un apellido
